### ISSUE TITLE
Can't install pymixconsole on Ubuntu !

### ISSUE THREAD

**Issue by maxgmrt** [csteinmetz1/pymixconsole#2]
Hi Christian, awesome things you're working on ! I'd like to get the pymix console to work properly on my ubuntu machine !
But when I try to install your package, I get this error :

`Collecting git+https://github.com/csteinmetz1/pymixconsole
  Cloning https://github.com/csteinmetz1/pymixconsole to /tmp/pip-yp39j1w_-build
Requirement already satisfied: scipy>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from pymixconsole==0.0.1)
Requirement already satisfied: numpy>=1.14.2 in ./.local/lib/python3.6/site-packages (from pymixconsole==0.0.1)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/usr/lib/python3/dist-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/usr/lib/python3.6/email/feedparser.py", line 175, in feed
    self._input.push(data)
  File "/usr/lib/python3.6/email/feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got `'NoneType' `

Thanks in advance !

**Comment by csteinmetz1** [comment]
Thanks for your interest in pymixconsole, @maxgmrt. 

I have not seen this error before. I just tried the install method on my local macOS machine and things worked as aspected. 
I am curious what version of pip you are on. Have you made sure to update to the latest version? 
```
pip install --upgrade pip
pip -V
```
Currently, I am on pip 20.2.3

**Comment by maxgmrt** [comment]
Thanks, it's working now !! My pip version was 9.x, so definitely super old ! Thanks for your quick answer !!!

**Comment by csteinmetz1** [comment]
Glad that worked. Please open any issues if you run into some trouble. Fair warning, there are no tests at the moment, and overall the package is a bit in alpha state. There is quite a bit of functionality already, but it may be easy to break things.
