### ISSUE TITLE
differentiable? 

### ISSUE THREAD

**Issue by lmaxwell** [csteinmetz1/pymixconsole#4]
I found no gradient implemented. Are these components differentiable?

**Comment by csteinmetz1** [comment]
Hi @lmaxwell, thanks for your interest! The pymixconsole library is not differentiable. It includes an implementation of traditional mixing console DSP. We use this library to generate the training data for our neural audio effects, which we use in our differentiable mixing console. Unfortunately, we have not be able to provide code for the neural audio effects, but pymixconsole can be used to train such neural audio effects. 

For insights into the TCNs we use for audio effect modeling you can see another project, [auraloss](https://github.com/csteinmetz1/auraloss/tree/main/examples/compressor), where we provide code for modeling a dynamic range compressor.

**Comment by lmaxwell** [comment]
Thanks for your clear explanation!
